# Generated by Django 4.2.3 on 2023-08-18 10:25

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import oauth2_provider.generators
import oauth2_provider.models
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CommentsSentimentanalysis",
            fields=[
                (
                    "comment_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("comment", models.TextField(blank=True, null=True)),
                ("sentiment", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "Comments_SentimentAnalysis",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Monthlystats",
            fields=[
                (
                    "monthly_stats_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "channel_subs",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "overall_views",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "MonthlyStats",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Scaninfo",
            fields=[
                ("scan_index", models.AutoField(primary_key=True, serialize=False)),
                ("scan_id", models.CharField(blank=True, max_length=255, null=True)),
                ("channel_id", models.CharField(blank=True, max_length=255, null=True)),
                ("phase", models.CharField(blank=True, max_length=255, null=True)),
                ("start_time", models.CharField(blank=True, max_length=255, null=True)),
                ("end_time", models.CharField(blank=True, max_length=255, null=True)),
                ("success", models.IntegerField(blank=True, null=True)),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "ScanInfo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="VideoRankings",
            fields=[
                (
                    "vid_rank_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("keyword", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "results_vidid",
                    models.CharField(
                        blank=True, db_column="results_vidID", max_length=255, null=True
                    ),
                ),
                (
                    "results_vidurl",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "results_vidtitle",
                    models.CharField(
                        blank=True,
                        db_column="results_vidTitle",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "results_viddesc",
                    models.TextField(
                        blank=True, db_column="results_vidDesc", null=True
                    ),
                ),
                (
                    "results_vidduration",
                    models.CharField(
                        blank=True,
                        db_column="results_vidDuration",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "results_vidviewcnt",
                    models.CharField(
                        blank=True,
                        db_column="results_vidViewcnt",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "results_viddt",
                    models.CharField(
                        blank=True, db_column="results_vidDt", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "Video_Rankings",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Videos",
            fields=[
                (
                    "vid_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("vid_title", models.CharField(blank=True, max_length=255, null=True)),
                ("vid_view_cnt", models.IntegerField(blank=True, null=True)),
                ("vid_like_cnt", models.IntegerField(blank=True, null=True)),
                ("vid_comment_cnt", models.IntegerField(blank=True, null=True)),
                ("vid_url", models.CharField(blank=True, max_length=255, null=True)),
                ("vid_desc", models.TextField(blank=True, null=True)),
                (
                    "vid_duration",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vid_published_at",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vid_thumbnail",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "Videos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Videostats",
            fields=[
                ("video_stats_id", models.AutoField(primary_key=True, serialize=False)),
                ("vid_id", models.CharField(blank=True, max_length=255, null=True)),
                ("date", models.CharField(blank=True, max_length=255, null=True)),
                ("vid_title", models.CharField(blank=True, max_length=255, null=True)),
                ("vid_view_cnt", models.IntegerField(blank=True, null=True)),
                ("vid_like_cnt", models.IntegerField(blank=True, null=True)),
                ("vid_comment_cnt", models.IntegerField(blank=True, null=True)),
                ("category", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "db_table": "VideoStats",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "username",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", core.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="scanTable",
            fields=[
                (
                    "scan_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                (
                    "channel_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("scan_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Channels",
            fields=[
                (
                    "scan_id",
                    models.OneToOneField(
                        db_column="scan_id",
                        max_length=255,
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="core.scantable",
                    ),
                ),
                (
                    "channel_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "channel_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("channel_description", models.TextField(blank=True, null=True)),
                ("total_videos_count", models.IntegerField(blank=True, null=True)),
                ("total_views_count", models.BigIntegerField(blank=True, null=True)),
                ("total_subs_count", models.BigIntegerField(blank=True, null=True)),
                ("partial_likes_count", models.IntegerField(blank=True, null=True)),
                ("partial_comments_count", models.IntegerField(blank=True, null=True)),
                ("partial_views_count", models.BigIntegerField(blank=True, null=True)),
                (
                    "channel_created_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("channel_logo_url", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Channels",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="EmojiFrequency",
            fields=[
                (
                    "vid",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="core.videos",
                    ),
                ),
                ("highlvl_freq", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "Emoji_Frequency",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="CustomApplication",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "client_id",
                    models.CharField(
                        db_index=True,
                        default=oauth2_provider.generators.generate_client_id,
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "redirect_uris",
                    models.TextField(
                        blank=True, help_text="Allowed URIs list, space separated"
                    ),
                ),
                (
                    "post_logout_redirect_uris",
                    models.TextField(
                        blank=True,
                        help_text="Allowed Post Logout URIs list, space separated",
                    ),
                ),
                (
                    "client_type",
                    models.CharField(
                        choices=[
                            ("confidential", "Confidential"),
                            ("public", "Public"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "authorization_grant_type",
                    models.CharField(
                        choices=[
                            ("authorization-code", "Authorization code"),
                            ("implicit", "Implicit"),
                            ("password", "Resource owner password-based"),
                            ("client-credentials", "Client credentials"),
                            ("openid-hybrid", "OpenID connect hybrid"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "client_secret",
                    oauth2_provider.models.ClientSecretField(
                        blank=True,
                        db_index=True,
                        default=oauth2_provider.generators.generate_client_secret,
                        help_text="Hashed on Save. Copy it now if this is a new secret.",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("skip_authorization", models.BooleanField(default=False)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "algorithm",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "No OIDC support"),
                            ("RS256", "RSA with SHA-2 256"),
                            ("HS256", "HMAC with SHA-2 256"),
                        ],
                        default="",
                        max_length=5,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
