# Generated by Django 4.2.3 on 2023-08-18 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scantable",
            name="scan_date",
            field=models.CharField(max_length=255),
        ),
    ]
