# Generated by Django 4.2.3 on 2023-08-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_user_profile_delete_customapplication"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="profile",
        ),
        migrations.AddField(
            model_name="user",
            name="google_extra_data",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
