# Generated by Django 4.2.3 on 2023-08-14 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_videos_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videos",
            options={"managed": False},
        ),
    ]
