# Generated by Django 4.2.3 on 2023-08-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_remove_user_profile_user_google_extra_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="google_extra_data",
            field=models.TextField(blank=True, null=True),
        ),
    ]
