# Generated by Django 4.2.3 on 2023-08-14 18:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_user_uuid_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="otp",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
