# Generated by Django 4.2.3 on 2023-08-15 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_user_otp_remove_user_phone_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScanTable",
            fields=[
                (
                    "scan_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "scan_date_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "scan_channel",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
